stages:          # Liste des étapes pour les jobs
  - build

build-job:       # Ce job s'exécute dans l'étape de build
  stage: build
  image: maven:3.8.7-openjdk-17-slim  # Utilise une image Docker Maven 3.8.7 avec JDK 17
  script:
    - mvn clean install      # Exécute la commande Maven
