stages:
  - build
  - analyze

build:
  stage: build
  image: maven:3.8.5-jdk-17
  script:
    - mvn clean package
  only:
    - mouad  # ou 'branches', pour exécuter sur toutes les branches

sonar:
  stage: analyze
  image: maven:3.8.5-jdk-17
  script:
    - mvn sonar:sonar -Dsonar.projectKey=mouadmakboul_multistagingDockerfile_automatisatebuilddeimagedocker -Dsonar.organization=mouadmakboul -Dsonar.login=0c758928bdc82e962b02e2c748702c5e9b899131
  only:
    - mouad  # ou 'branches', pour exécuter sur toutes les branches
