version: '3.8'

services:
  frontend:
    image: fronte
    container_name: frontend
    ports:
      - "8010:80"
  app:
    build:                     # Ajout de la section build
      context: .               # Contexte de construction (répertoire actuel)
      dockerfile: Dockerfile   # Nom de votre Dockerfile
    image: imagemulti:v2
    container_name: spring_boot
    ports:
      - "1000:1000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: jaimeislam10
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jaimeislam10
    volumes:
      - C:/Users/hp/postgres_dataa:/var/lib/postgresql/data

volumes:
  postgres_dataa:
