name: CI Pipeline

on:
  push:
    branches:
      - mouad

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: jaimeislam10  # Change ça selon tes besoins
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -Dspring.datasource.url=jdbc:postgresql://localhost:5432/testdb -Dspring.datasource.username=postgres -Dspring.datasource.password=jaimaieslam10

      - name: Build Docker Image
        run: docker build -t mouadmakboul8413/mon-image .

      - name: Run SonarCloud Analysis
        run: mvn sonar:sonar -Dsonar.projectKey=mouadmakboul_multistagingDockerfile_automatisatebuilddeimagedocker -Dsonar.organization=mouadmakboul -Dsonar.login=${{ secrets.SONAR_TOKEN }}
