name: CI Pipeline

on:
  push:
    branches:
      - mouad  # Change cela si tu utilises une autre branche

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker Image
        run: docker build -t mouadmakboul8413/mon-image .

      - name: Run SonarCloud Analysis
        run: mvn sonar:sonar -Dsonar.projectKey=mouadmakboul_multistagingDockerfile_automatisatebuilddeimagedocker -Dsonar.organization=mouadmakboul -Dsonar.login=${{ secrets.SONAR_TOKEN }}
